services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: squaredle
      POSTGRES_USER: squaredle
      POSTGRES_PASSWORD: squaredle

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .

    depends_on:
      - postgres
#
#    env_file: .env

    environment:
      DATABASE_URL: postgresql+psycopg://squaredle:squaredle@postgres:5432/squaredle
      RAE_API_KEY: rae_live_bbd43a71d5fecdbe57d31cd233b5518e6e3c231d0c922584d1fee2a3a3c1a88d

    ports:
      - "8000:8000"

  frontend:
    build: ./frontend

    depends_on:
      - api

    ports:
      - "5500:80"

volumes:
  postgres_data: