"""add bonus column

Revision ID: 0b450b7b4a08
Revises: 107dc8861149
Create Date: 2026-06-29 15:43:50.489791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b450b7b4a08'
down_revision: Union[str, Sequence[str], None] = '107dc8861149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("found_words", sa.Column(
            "bonus",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('found_words', 'bonus')
    # ### end Alembic commands ###
