"""add bonus score to session

Revision ID: 836b926e7463
Revises: 0b450b7b4a08
Create Date: 2026-07-01 18:50:34.224589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836b926e7463'
down_revision: Union[str, Sequence[str], None] = '0b450b7b4a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('bonus_score', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sessions', sa.Column('bonus_found_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'bonus_found_count')
    op.drop_column('sessions', 'bonus_score')
    # ### end Alembic commands ###
