"""initial schema

Revision ID: a88e67692bc6
Revises: 
Create Date: 2026-06-25 22:24:21.529406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a88e67692bc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('puzzle_date', sa.Date(), nullable=False),
    sa.Column('puzzle_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('solution_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puzzle_date')
    )
    op.create_index('ix_puzzles_puzzle_date', 'puzzles', ['puzzle_date'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('puzzle_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('found_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_puzzle_id'), 'sessions', ['puzzle_id'], unique=False)
    op.create_table('found_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('found_at', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'word', name='uq_session_word')
    )
    op.create_index(op.f('ix_found_words_session_id'), 'found_words', ['session_id'], unique=False)
    op.create_index(op.f('ix_found_words_word'), 'found_words', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_found_words_word'), table_name='found_words')
    op.drop_index(op.f('ix_found_words_session_id'), table_name='found_words')
    op.drop_table('found_words')
    op.drop_index(op.f('ix_sessions_puzzle_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_puzzles_puzzle_date', table_name='puzzles')
    op.drop_table('puzzles')
    # ### end Alembic commands ###
